version: '3.8'

services:
  nginx:
    image: nginx:1.22.1
    ports:
      - 8083:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: lemp
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
        test: mysqladmin ping -h 128.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
        interval: 5s
        retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8085:80
    environment:
        PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata: 
